---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by seancheey.
--- DateTime: 10/1/20 2:38 AM
---

--- @class Copier
---@type Copier
local Copier = {}

--- @generic T
--- @param orig T
--- @return T
function Copier.deep_copy(orig, keep_metatable)
    local orig_type = type(orig)
    local copy
    if orig_type == 'table' then
        copy = {}
        for orig_key, orig_value in next, orig, nil do
            copy[Copier.deep_copy(orig_key)] = Copier.deep_copy(orig_value)
        end
        if keep_metatable then
            setmetatable(copy, Copier.deep_copy(getmetatable(orig)))
        end
    else
        -- number, string, boolean, etc
        copy = orig
    end
    return copy
end

--- @generic T
--- @param orig T
--- @return T
function Copier.shallow_copy(orig)
    local orig_type = type(orig)
    local copy
    if orig_type == 'table' then
        copy = {}
        for orig_key, orig_value in pairs(orig) do
            copy[orig_key] = orig_value
        end
    else
        copy = orig
    end
    return copy
end

return Copier