---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by seancheey.
--- DateTime: 10/10/20 1:32 AM
---

--- @class DirectionHelper
--- @type DirectionHelper
local DirectionHelper = {}
DirectionHelper.allStraightDirections = { 0, 2, 4, 6 }

--- shift direction with number of 45 degrees
local function shift(direction, n45deg)
    return (direction + n45deg) % 8
end

--- @return defines.direction
function DirectionHelper.reverseOf(direction)
    return shift(direction, 4)
end

--- @return defines.direction[]
function DirectionHelper.listFrontLeftRightOf(direction)
    return { direction, shift(direction, 2), shift(direction, 6) }
end

--- @return defines.direction[]
function DirectionHelper.listTailLeftRightOf(direction)
    return { shift(direction, 4), shift(direction, 2), shift(direction, 6) }
end

function DirectionHelper.listReverseOf(direction)
    return { DirectionHelper.reverseOf(direction) }
end

function DirectionHelper.listFrontOf(direction)
    return { direction }
end

function DirectionHelper.listAllStraightDirectionOf(direction)
    return DirectionHelper.allStraightDirections
end

return DirectionHelper
