---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by seancheey.
--- DateTime: 9/30/20 3:46 AM
---


--- @class Pointer a simple reference pointer
local Pointer = {}

--- @generic T
--- @param val T
--- @return T[]
function Pointer.new(val)
    return { val }
end

--- @generic T
--- @param ref T[]
--- @return T
function Pointer.get(ref)
    return ref[1]
end

function Pointer.set(ref, value)
    ref[1] = value
end

return Pointer